eureka:
 client:
   service-url:
       defaultZone: http://localhost:8761/eureka
 instance:
   hostname: productserver #域定义链接
datasource:
  driver-class-name: com.mysql.cj.jdbc.Driver
  username: root
  password: seen328266
  url: jdbc:mysql://localhost:3306/weixinsell?serverTimezone=UTC&characterEncoding=utf-8&useSSL=false
jpa:
  show-sql: true
server:
 port: 8081

